### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by idavis** [open-horizon/cogwerx-jetson-tx2#12]
Would you be willing to share this under the [MIT license](https://opensource.org/licenses/MIT)?  Right now, you are [retaining all rights and allowing no reuse](https://choosealicense.com/no-permission/) through a lack of license. These scripts would be very helpful to the community.

Thank you,

Ian Davis

**Comment by datajerk** [comment]
All open-horizon projects are covered under the EPL.  Give the team a few days to get the license files added to the missing repos.

**Comment by idavis** [comment]
@datajerk Thank you!

**Comment by idavis** [comment]
License was applied out of thread.
