### ISSUE TITLE
Build of NVIDIA's Caffe fails

### ISSUE THREAD

**Issue by shazz** [open-horizon/cogwerx-jetson-tx2#7]
Hi,
When I try to build the container with NVIDIA's Caffe, I have the following errors:

```
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_regex

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
```

I fixed it by adding: libboost-regex-dev in the apt-get install

Then.. a few steps after I have another error:

```
...
-- Found Snappy  (include: /usr/include, library: /usr/lib/aarch64-linux-gnu/libsnappy.so)
CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find JPEGTurbo (missing: JPEGTurbo_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/FindJPEGTurbo.cmake:18 (find_package_handle_standard_args)
  cmake/Dependencies.cmake:57 (find_package)
  CMakeLists.txt:66 (include)


-- Configuring incomplete, errors occurred!
See also "/caffe/build/CMakeFiles/CMakeOutput.log".
See also "/caffe/build/CMakeFiles/CMakeError.log".
The command '/bin/sh -c cmake ../ -DCUDA_ARCH_NAME="Manual" -DCUDA_ARCH_BIN="52 60" -DCUDA_ARCH_PTX="60"' returned a non-zero code: 1
```

And this one.... I did not find how to fix it (I thought adding apt-get install libjpeg-dev libjpeg-turbo8-dev libjpeg-turbo8 libjpeg8-dev would solve it but no)

Thanks !

matt

**Comment by shazz** [comment]
I found out on the Nvidia Caffe github that only version 0.15 is supported by digits so I added:
`RUN git clone http://github.com/NVIDIA/caffe -b 'caffe-0.15'`

Which... fails but differently:
```

[ 40%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/io.cpp.o
/tmp/ccxdrod2.s: Assembler messages:
/tmp/ccxdrod2.s:1533: Error: unknown mnemonic `pause' -- `pause'
/tmp/ccxdrod2.s:1857: Error: unknown mnemonic `pause' -- `pause'
/tmp/ccxdrod2.s:2204: Error: unknown mnemonic `pause' -- `pause'
/tmp/ccxdrod2.s:2679: Error: unknown mnemonic `pause' -- `pause'
/tmp/ccxdrod2.s:4226: Error: unknown mnemonic `pause' -- `pause'
/tmp/ccxdrod2.s:5069: Error: unknown mnemonic `pause' -- `pause'
/tmp/ccxdrod2.s:5320: Error: unknown mnemonic `pause' -- `pause'
/tmp/ccxdrod2.s:5441: Error: unknown mnemonic `pause' -- `pause'
src/caffe/CMakeFiles/caffe.dir/build.make:842: recipe for target 'src/caffe/CMakeFiles/caffe.dir/util/gpu_memory.cpp.o' failed
make[2]: *** [src/caffe/CMakeFiles/caffe.dir/util/gpu_memory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:272: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[1]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c make --jobs=4' returned a non-zero code: 2
```

Looks to be assembly issues.... 
Do you remember which version of Caffe you have recompiled?

**Comment by shazz** [comment]
ok... just saw that mutex.patch..... Why don't you apply it in the Dockerfile ? :)
Testing it...

**Comment by chrod** [comment]
Thank you for the comments and troubleshooting info!
For some reason that patch was taken out of the Dockerfile.nvidia.caffe.  I've added it back in. 
That version of Caffe was likely 0.15 at the time of initial build, as you found out.  I've stipulated that also in the updated Dockerfile.nvidia.caffe.

Check out the updated files in the latest commit for [JetPack3.2-R28.2-RC-libs](https://github.com/open-horizon/cogwerx-jetson-tx2/tree/JetPack3.2-R28.2-RC-libs)  (you may have already reached that point in the build).

I'll push updated containers for:
- `openhorizon/aarch64-tx2-cudabase:JetPack3.2-RC`
- `openhorizon/aarch64-tx2-caffe:JetPack3.2-RC`
- `openhorizon/aarch64-tx2-nvidia-caffe:JetPack3.2-RC`
- `openhorizon/aarch64-tx2-opencv4tegra-caffe:JetPack3.2-RC`

**Comment by shazz** [comment]
Thanks !
